name: firestore_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.15.7
  cupertino_icons: ^0.1.2
  date_format: ^1.0.6

#  google_sign_in: "3.0.4"
#  firebase_auth: ^0.5.11

  google_sign_in: ^4.0.1+1
  firebase_auth: ^0.8.1+1
  cloud_firestore: ^0.9.0+2
  flutter_launcher_icons: ^0.7.0

  flutter_circular_chart: ^0.1.0
  autocomplete_textfield: ^1.6.4
  queries: ^0.1.10

  # cloud_firestore: ^0.8.2+1

  # google_sign_in: "3.0.3"
  # firebase_auth: "0.5.9"
  # cloud_firestore: "0.7.0"

  # firebase_auth: ^0.7.0
  # cloud_firestore: ^0.8.2+3



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  iso: true
  image_path: "assets/images/ic_launcher.png"


flutter:

  uses-material-design: true
  assets:
    - assets/images/ic_launcher.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
